<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>stacy_py</name>
  <version>0.0.0</version>
  <description>ROS 2 gimbal robot that aims a directional antenna to locate hidden Bluetooth trackers.</description>
  <maintainer email="110917999+CashBailey@users.noreply.github.com">Cash Bailey</maintainer>
  <license>Proprietary</license>

  <!-- Build tool dependency for ament_python -->
  <buildtool_depend>ament_python</buildtool_depend>

  <!-- Execution dependency on rclpy -->
  <exec_depend>rclpy</exec_depend>

  <!-- Optional test dependencies -->
  <test_depend>ament_flake8</test_depend>
  <test_depend>pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
